### ISSUE TITLE
About CADA

### ISSUE THREAD

**Issue by xuebizei** [LinDixuan/CADA#1]
Thanks for your excellent work in text-to-image reid, but I found some problems in your work. About the models/cada.py, could you tell me where the class CADA is?

**Comment by LinDixuan** [comment]
It seems that we have uploaded a version with mistakes on github, sorry for
that. I will update a new version in two weeks.

gaopenghkbu ***@***.***> 于 2024年3月4日周一 下午8:03写道：

**Comment by xuebizei** [comment]
Thanks!

**Comment by LinDixuan** [comment]
We have updated our codes, thank you for your attention to our work.

gaopenghkbu ***@***.***> 于2024年3月6日周三 20:33写道：
