### ISSUE TITLE
question for missing train_clip_cuhk.py

### ISSUE THREAD

**Issue by shinian-023** [LinDixuan/CADA#2]
Thank you for your excellent work, but I have found that the evaluation file train_clip_cuhk.py is missing from the source code you provided. Can you provide this file? Thank you very much!

**Comment by LinDixuan** [comment]
Thank you, replace it with train.py would be ok.

shinian ***@***.***> 于2024年3月12日周二 11:12写道：

**Comment by shinian-023** [comment]
thanks~

**Comment by shinian-023** [comment]
@LinDixuan Sorry to bother you, but I used different batch sizes to train CADA on the CUHK dataset, including 24, 32, 48, 64, and 96. However, I did not achieve the local-matching inference Rank-1 score of 78.37 reported in the paper. The best Rank-1 score I obtained on the test set was 77.18. Could you please release the checkpoint files of CADA for the three datasets, or provide guidance on which parameters need to be adjusted and how to properly train CADA?

**Comment by LinDixuan** [comment]
@shinian-023 
Hi, you can download our checkpoints here:
cuhk_best.pth: https://drive.google.com/file/d/1MUuo21WnIIR8kkC0r3IHpmn6Y_SOtglQ/view?usp=sharing
icfg_best.pth: https://drive.google.com/file/d/1n8wboh6CmN2bSRwE1YaQ2Nhnq-ObqACX/view?usp=drive_link
I hope it can help you.
