### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by ErgastiAlex** [LinDixuan/CADA#5]
Thanks for your work,
Is it possible to have the checkpoints of the net without needing to re-train from scratch?

**Comment by LinDixuan** [comment]
Hi, you can download our checkpoints here: 
cuhk_best.pth: https://drive.google.com/file/d/1MUuo21WnIIR8kkC0r3IHpmn6Y_SOtglQ/view?usp=sharing 
icfg_best.pth: https://drive.google.com/file/d/1n8wboh6CmN2bSRwE1YaQ2Nhnq-ObqACX/view?usp=drive_link
I hope it can help you.
