### ISSUE TITLE
About  eval.bash

### ISSUE THREAD

**Issue by cookieApril** [LinDixuan/CADA#7]
Thanks for your excellent work in text-to-image reid, but I found some problems in your work. About the train.py , based on eval.bash.when i run eval.bash , make a error.
![error](https://github.com/LinDixuan/CADA/assets/137610216/98043f85-cf45-4530-819c-6bb29684d973)
In train.py I couldn't find this variable.Can you tell me where it is?
![1](https://github.com/LinDixuan/CADA/assets/137610216/5c29fba6-ade9-479f-b068-6c4ac70d3c83)

**Comment by LinDixuan** [comment]
The "score_test_glb_i2t" shall be deleted from inputs, I will update the codes.
